// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KoLighter
{
	internal sealed partial class Vsix
	{
		public const string Id = "KoLighter.a5df7c25-c380-4c34-8d09-3270a936612e";
		public const string Name = "KoLighter";
		public const string Description = @"Empty VSIX Project.";
		public const string Language = "en-US";
		public const string Version = "1.0";
		public const string Author = "Andrija Eremic";
		public const string Tags = "";
	}
}
