// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace KoLighter
{
	/// <summary>
	/// Helper class that exposes all GUIDs used across VS Package.
	/// </summary>
	internal sealed partial class PackageGuids
	{
		public const string KoLighterString = "f15ea669-611a-45f6-bb62-856f678183d3";
		public static Guid KoLighter = new Guid(KoLighterString);
	}
	/// <summary>
	/// Helper class that encapsulates all CommandIDs uses across VS Package.
	/// </summary>
	internal sealed partial class PackageIds
	{
		public const int Toggle = 0x000A;
	}
}